seed:
max_peaks: 100
epochs: 50
batch_size: 100
lr_warmup_steps: 1000
lr: 1e-4
max_steps: 1e10
tasks:
  #- NaryTask
  #- nary_ab
  #- hidden_mz
  #- hidden_ab
  #- hidden_spectrum
  #- hidden_charge
  #- hidden_mass
  #- mass_competition
  #- Maldi
  #- resid_regr
  - VAE

# Downstream evaluation
steps_per_report: 15000
first_report:
  pretrain_execute: True
  only_dnv: False
  loadpath: # For continuing from previous denovo run
dnv_eval:
  execute: False
nn_eval:
  execute: True
  top_n: 10
  pooling: mean
  metric: cosine
  query_batch_size: 2048

# Logging
log_wandb: True
wandb_project: foundation
wandb_entity: joellapin

# Loading and Saving
loadpath:
svwts: True
svfreq: 1800
svgrad: False
debug: False
