seed:
max_peaks: 100
epochs: 2
steps_per_report: 10000
max_steps: 1e10
batch_size: 100
lr: 1e-4
tasks:
  - trinary_mz
  #- trinary_ab
  #- hidden_mz
  #- hidden_ab
  #- hidden_spectrum
  #- hidden_charge
  #- hidden_mass
  #- maldi
  #- resid_regr
downstream:
  #- denovo_ar

log_wandb: False
wandb_project: debug
wandb_entity: joellapin

load: False
loadpath:
log: False
svwts: False
svfreq: 1800
svgrad: False
debug: False
header: "PretrainV2-50M"
